### ISSUE TITLE
Transactions list for addresses is always empty

### ISSUE THREAD

**Issue by schildbach** [janoside/btc-rpc-explorer#188]
**Describe the bug**

When I click on an address, the transactions list on `/address/…` is always empty. Obviously it should contain at least one entry.

I have almost identical installations for mainnet and testnet; the issue appears on both. The connection to bitcoind appears to work fine. Both bitcoind and ElectrumX are fully synched.

In the logfile, for each `/address/…` request this error appears:

```
btcexp:error Error 21307ws70sg: TypeError: Cannot read property 'result' of undefined, json: {}
```

**Environment (please complete the following information):**

 - btc-rpc-explorer: 1.1.9
 - Bitcoin Core / Node Version: 0.19.0.1
 - ElectrumX: 1.14.0

I'm using the Docker images for all of the above, built myself from the respective git tags. No customizations.
 
**Configuration file content**

For testnet:

```
  btc-rpc-explorer:
    image: btc-rpc-explorer:1.1.9
    depends_on:
      - bitcoind
      - electrumx
    environment:
      - BTCEXP_COIN=BTC
      - BTCEXP_HOST=0.0.0.0
      - BTCEXP_BITCOIND_URI=bitcoin://user:xxx@bitcoind:18332
      - BTCEXP_ADDRESS_API=electrumx
      - BTCEXP_ELECTRUMX_SERVERS=tcp://electrumx:51001
      - BTCEXP_PRIVACY_MODE=true
```

For mainnet:

```
  btc-rpc-explorer:
    image: my/btc-rpc-explorer:1.1.9
    depends_on:
      - bitcoind
      - electrumx
    environment:
      - BTCEXP_COIN=BTC
      - BTCEXP_HOST=0.0.0.0
      - BTCEXP_BITCOIND_URI=bitcoin://user:xxx@bitcoind:8332
      - BTCEXP_ADDRESS_API=electrumx
      - BTCEXP_ELECTRUMX_SERVERS=tcp://electrumx:50001
      - BTCEXP_PRIVACY_MODE=true
```
