### ISSUE TITLE
Automate docker build and publish.

### ISSUE THREAD

**Issue by Kukks** [janoside/btc-rpc-explorer#62]
Currently, there is one remotely close published docker image of this repo and it seems to be outdated. Seeing as you have a dockerfile in the project already, I'd recommend you configure an automated build on Dockerhub. See https://docs.docker.com/docker-hub/builds/#prerequisites

**Comment by loganmarchione** [comment]
@janoside I was also wondering about this. I would love to run this in Docker vs installing manually with NPM.

Also, there are a bunch of [no-name builds of this out there](https://hub.docker.com/search?q=btc-rpc-explorer&type=image), would be nice to have an officially blessed container.

**Comment by loganmarchione** [comment]
FYI if anyone finds this.

My main issue was having to clone the repo first. However, Docker Compose allows you to build from a remote URL without cloning the repo first. 

```
version: '3'
services:
  btc-rpc-explorer:
    container_name: btc-rpc-explorer
    restart: unless-stopped
    environment:
      - BTCEXP_HOST=0.0.0.0
    ports:
      - '3002:3002'
    build:
      context: https://github.com/janoside/btc-rpc-explorer.git
      dockerfile: Dockerfile
```
